"""Add is_active for soft delete to Order

Revision ID: 898e26d434e9
Revises: d5db45810289
Create Date: 2025-05-25 07:34:21.643492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898e26d434e9'
down_revision: Union[str, None] = 'd5db45810289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_active', sa.Boolean(), nullable=False,server_default=sa.text('1')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_active')
    # ### end Alembic commands ###
