"""create other tables and adding relationship to client

Revision ID: c9fb0db38c03
Revises: fcfced50bbe8
Create Date: 2025-05-24 03:56:22.401644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from luestilo_api.models import JSONList


# revision identifiers, used by Alembic.
revision: str = 'c9fb0db38c03'
down_revision: Union[str, None] = 'fcfced50bbe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('valor_de_venda', sa.Float(), nullable=False),
    sa.Column('codigo_de_barras', sa.String(), nullable=False),
    sa.Column('secao', sa.String(), nullable=False),
    sa.Column('estoque_inicial', sa.Integer(), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('imagens', JSONList(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_de_barras')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_products',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_order', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_products')
    op.drop_table('orders')
    op.drop_table('products')
    # ### end Alembic commands ###
