"""Add whatsapp fields to Client model

Revision ID: f5af6ea50c9b
Revises: 898e26d434e9
Create Date: 2025-05-26 01:57:02.009174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5af6ea50c9b'
down_revision: Union[str, None] = '898e26d434e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('aceita_notificacoes_whatsapp', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'aceita_notificacoes_whatsapp')
    # ### end Alembic commands ###
